#!/usr/bin/env python3
import json
from datetime import datetime
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = json.loads((ROOT / 'artifacts.json').read_text())

def date_label(a):
    return str(a.get('updated_at') or a.get('created_at') or '')[:10]

def card(a):
    tags = ''.join(f'<span>{escape(str(t))}</span>' for t in (a.get('tags') or [])[:5])
    meta = ''.join(f'<span>{escape(str(x))}</span>' for x in [a.get('category'), date_label(a), a.get('status'), a.get('template')] if x)
    href = a.get('url') or a.get('path') or '#'
    return f'''        <article class="card" data-category="{escape(str(a.get('category','')))}">
          <div class="meta">{meta}</div>
          <h2><a href="{escape(href)}">{escape(str(a.get('title','Untitled')))}</a></h2>
          <p>{escape(str(a.get('summary','')))}</p>
          <div class="tags">{tags}</div>
        </article>'''

cats = ['all'] + sorted({a.get('category') for a in ARTIFACTS if a.get('category')})
button_bits = []
for c in cats:
    active = 'class="active" ' if c == 'all' else ''
    button_bits.append(f'<button {active}data-filter="{escape(c)}">{escape(c)}</button>')
buttons = ''.join(button_bits)
cards = '\n'.join(card(a) for a in ARTIFACTS)
now = datetime.now().strftime('%d %b %Y, %H:%M IST')
html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Hermes Artifacts</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&family=Geist+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>
:root{{--bg:#03040a;--panel:rgba(13,17,29,.82);--panel2:rgba(20,25,42,.78);--line:rgba(255,255,255,.11);--text:#f7f8ff;--muted:#9aa4ba;--accent:#9b87ff;--good:#66e3b4;--shadow:0 24px 80px rgba(0,0,0,.42)}}
*{{box-sizing:border-box}}body{{margin:0;font-family:Geist,system-ui,sans-serif;background:radial-gradient(circle at 20% -10%,rgba(155,135,255,.22),transparent 34%),radial-gradient(circle at 80% 5%,rgba(102,227,180,.12),transparent 30%),linear-gradient(180deg,#03040a,#070a12 50%,#03040a);color:var(--text)}}
body:before{{content:"";position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:44px 44px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.55),transparent 70%)}}
.wrap{{max-width:1180px;margin:0 auto;padding:48px 22px 80px;position:relative}}.hero{{padding:34px;border:1px solid var(--line);background:linear-gradient(135deg,rgba(255,255,255,.09),rgba(255,255,255,.035));border-radius:28px;box-shadow:var(--shadow)}}
.kicker{{font:600 12px/1 Geist Mono,monospace;color:var(--good);letter-spacing:.14em;text-transform:uppercase}}h1{{font-size:clamp(42px,7vw,78px);line-height:.92;margin:12px 0 14px;letter-spacing:-.06em}}.lead{{max-width:760px;color:var(--muted);font-size:18px;line-height:1.65}}
.controls{{display:flex;gap:10px;flex-wrap:wrap;margin:28px 0}}button{{border:1px solid var(--line);background:rgba(255,255,255,.055);color:var(--text);padding:10px 14px;border-radius:999px;font-weight:650;cursor:pointer}}button:hover,button.active{{border-color:rgba(155,135,255,.7);background:rgba(155,135,255,.18)}}
.grid{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}}.card{{border:1px solid var(--line);background:var(--panel);border-radius:22px;padding:20px;box-shadow:0 12px 40px rgba(0,0,0,.25)}}.card:hover{{background:var(--panel2);transform:translateY(-1px)}}.meta{{display:flex;gap:8px;flex-wrap:wrap;color:var(--muted);font:600 11px/1.2 Geist Mono,monospace;text-transform:uppercase}}h2{{font-size:21px;line-height:1.16;letter-spacing:-.03em;margin:14px 0 8px}}a{{color:inherit;text-decoration:none}}a:hover{{color:var(--accent)}}p{{color:var(--muted);line-height:1.55}}.tags{{display:flex;gap:6px;flex-wrap:wrap;margin-top:14px}}.tags span{{font:600 11px Geist Mono,monospace;color:#c8d0ff;background:rgba(155,135,255,.12);border:1px solid rgba(155,135,255,.2);padding:6px 8px;border-radius:999px}}footer{{margin-top:36px;color:var(--muted);font:13px Geist Mono,monospace}}@media(max-width:820px){{.grid{{grid-template-columns:1fr}}.hero{{padding:24px}}}}
</style></head><body><main class="wrap"><section class="hero"><div class="kicker">Hermes artifact hub</div><h1>Readable outputs, not chat walls.</h1><p class="lead">Saved reports, dashboards, and one-off research artifacts generated by Hermes. Telegram stays short; this hub keeps the full reading surface.</p></section><div class="controls">{buttons}</div><section class="grid">
{cards}</section><footer>Generated {escape(now)} · {len(ARTIFACTS)} artifacts indexed · <a href="artifacts.json">manifest</a></footer></main><script>
document.querySelectorAll('button[data-filter]').forEach(b=>b.onclick=()=>{{document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let f=b.dataset.filter;document.querySelectorAll('.card').forEach(c=>c.style.display=(f==='all'||c.dataset.category===f)?'block':'none')}})
</script></body></html>'''
(ROOT / 'index.html').write_text(html)
print(f'wrote index with {len(ARTIFACTS)} artifacts and categories: {", ".join(cats)}')
